export const RUNNER_CLUBS = [
  "None",
  "Aarya Dashers",
  "Aero Runners",
  "Airport Runners, Kochi",
  "Anjaneya Runners",
  "Annur Runners",
  "ANT Runners",
  "ARM STRONG FITNESS CHEEKILODE",
  "Ascend Runners",
  "Ascent Runners",
  "ASICS Running Club Chennai",
  "Athletico De Alleppey",
  "Avinashi Runners Club",
  "Bailwan Runners",
  "Ballari Runners",
  "Bandit Runners",
  "Baroda Runners",
  "Belagavi Endurance Sports",
  "Blue Mount Runners",
  "BNI Palakkad",
  "BOB",
  "Boisterous Runners, Coimbatore",
  "CG Eternia runners",
  "Changanassery Runners Club (CRC)",
  "Chennai Cyclists",
  "Chennai Joy riders",
  "Chennai Runners - Ambattur Arimass",
  "Chennai Runners - Bessie Flyers",
  "Chennai Runners - Chromepet Cheetahs",
  "Chennai Runners - Coastal Runners",
  "Chennai Runners - Kilpauk Striders",
  "Chennai Runners - Marina Minnals",
  "Chennai Runners - Mogappair Fitness Circle",
  "Chennai Runners - Nungambakkam Nitros",
  "Chennai Runners - OMR Trailblazers",
  "Chennai Runners - Pettai Rappers",
  "Chennai Runners - Pillar Pacers",
  "Chennai Runners - Porur Racers",
  "Chennai Runners - T.Nagar Trendsetters",
  "Chennai Runners - Tambaram Thunderbolts",
  "Chennai Runners - Tower Twisters",
  "Chennai Runners - Vibrant Velachery",
  "Chennai Trekking Club (CTC)",
  "Cherai Runners",
  "Chungam Real Runners",
  "Ciclo Cafe",
  "CMC",
  "Coimbatore Runners",
  "Cool Runners",
  "Covai Runners & Riders Club (CRRC)",
  "Cycling Yogis",
  "Cycopaths",
  "Dream Runners - AIRPORT DREAMERS",
  "Dream Runners - ANNA NAGAR DREAMERS",
  "Dream Runners - AVADI DREAMERS",
  "Dream Runners - BESSIE DREAMERS",
  "Dream Runners - BOAT CLUB DREAMERS",
  "Dream Runners - MARINA DREAMERS",
  "Dream Runners - MEDAVAKKAM DREAMERS",
  "Dream Runners - MRC DREAMERS",
  "Dream Runners - OMR DREAMERS",
  "Dream Runners - RUN T NAGAR RUN",
  "Dream Runners - VELACHERY DREAMERS",
  "Dream Runners - VMR DREAMERS",
  "EC Runners",
  "Erode Runners",
  "F3 Fitness Group",
  "Flying Feet",
  "Fort Kochi Runners",
  "Free Runners",
  "Friends Fun Fitness",
  "G3",
  "GiB Runners Club – Erode",
  "Gobi Riders Club",
  "Groundmates",
  "HAPPY FEET",
  "Heaven Runners",
  "Hyderabad Runners",
  "Idea Runners Club",
  "IFiT Club – Erode",
  "Iten",
  "Jayanagar Jaguars",
  "Jolly Runners",
  "Just Move Club, Kollam",
  "Kalamassery Runners group",
  "Kalangal Runners",
  "Kangayam Runners",
  "Karimangalam Runners Club",
  "Karur Runner Club",
  "Kavach Runners",
  "Kolkata Runners",
  "Kottakkal Runners Club",
  "Kottayam Runners",
  "Kovaipudur Runners",
  "Madras Mustangs",
  "Madras Randonneurs",
  "Madrascals",
  "Malappuram Runners Club",
  "Maradu Runners",
  "Marina Runnerz",
  "MAVS",
  "Mongrels",
  "Motley Crew",
  "Mumbai Road Runners",
  "MWC Runners Club",
  "Nellai Runners",
  "Nomadic Nilgrians Running Club",
  "Olympic Runners",
  "OMR Athletes",
  "Ondipudur Runners",
  "Orange Runners, Ernakulam",
  "Osian Runners",
  "Pace N Race club",
  "Pacemakers",
  "Panampilly Nagar Runners, Kochi",
  "Pedalbeat",
  "Periyar Runners",
  "Phoenix Runners",
  "Pinkathon",
  "Pollachi Athletic Club",
  "PVS Iris Runners",
  "QR Runners",
  "Quad Runners",
  "Rocket Runners",
  "Royal Runners Calicut",
  "Run for Coffee",
  "Runners 360",
  "Runners High",
  "Salem Runners",
  "Sathy runners",
  "SBC Striders",
  "SBI Runners",
  "Sivagiri Runners",
  "Skechers Go Run Club, Bangalore",
  "Soles of Bangalore",
  "Soles of Cochin",
  "Soles of Kollam",
  "Spartans Marathon Boys, Karumathampatti",
  "Stadium Runners Kaloor",
  "Striders",
  "Tamilnadu Cycling Club",
  "Team Bisons",
  "Teenduruns",
  "The Mountain Gaurs Running Club",
  "Tirupur Phoenix Runners",
  "Tirupur Runners",
  "Trichy Runners",
  "UNIS Running",
  "Universal Runners club, Coimbatore",
  "Velocite",
  "Vizag Sole Runners",
  "Warrior Runners",
  "Wheels of Kollam",
  "Zen Runners",
  "Others",
];
